services:
  - type: web
    name: hello-flask-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: FRONTEND_URL
        value: https://hello-flask-frontend.onrender.com
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
    autoDeploy: true

  - type: web
    name: hello-flask-frontend
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npx serve -s frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://hello-flask-backend.onrender.com
    autoDeploy: true
