services:
  - type: web
    name: hello-flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://hello-flask-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
